version: '3'

services:
  web:
    image: nexblu/illustra-line-api:24.7.1
    ports:
      - "5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IllustraLine
    ports:
      - "5432"
