version: '3'

services:
  web:
    build: .
    ports:
      - "5000"
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - POSTGRESQL_URL=postgresql://postgres:postgres@db:5432/IllustraLine
    volumes:
      - .:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: IllustraLine
    ports:
      - "5432"
